FROM python:3.11-slim
WORKDIR /app
ENV PIP_NO_CACHE_DIR=1
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY src ./src
ENV PORT=8084
EXPOSE 8084
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8084"]
